from __future__ import annotations
import os
from datetime import datetime
import pandas as pd
import streamlit as st
from pathlib import Path
import pandas as pd

from cb_monitor import load_market_data, add_breakout_flags, apply_filters
from gemini_report import generate_report, generate_company_summary


def load_history_summary():
    daily_dir = Path("data/daily")
    rows = []
    if not daily_dir.exists():
        return pd.DataFrame()
    for f in sorted(daily_dir.glob("*.csv")):
        try:
            x = pd.read_csv(f)
            if "CB價格" not in x.columns:
                continue
            price = pd.to_numeric(x["CB價格"], errors="coerce")
            total = int(price.notna().sum())
            le105 = int((price <= 105).sum())
            lt100 = int((price < 100).sum())
            b105_110 = int(((price > 105) & (price <= 110)).sum())
            b110_120 = int(((price > 110) & (price <= 120)).sum())
            gt120 = int((price > 120).sum())
            rows.append({
                "日期": f.stem,
                "總檔數": total,
                "≤105元": le105,
                "≤105元占比": le105 / total if total else 0,
                "<100元": lt100,
                "105–110元": b105_110,
                "110–120元": b110_120,
                ">120元": gt120,
            })
        except Exception:
            pass
    return pd.DataFrame(rows)

st.set_page_config(page_title="Taiwan CB Relative Value Dashboard", page_icon="📊", layout="wide")

st.markdown("""
<style>
.block-container {padding-top: 1.5rem; padding-bottom: 2rem;}
.small-muted {color:#64748b;font-size:0.85rem;}
.breakout {background:#fff7ed;border-left:5px solid #f97316;padding:0.65rem 0.9rem;border-radius:0.35rem;margin:0.25rem 0;}
</style>
""", unsafe_allow_html=True)

st.title("📊 Taiwan CB Relative Value Dashboard")
st.caption("台灣可轉債主管版｜Market Overview · Scanner · Bond Detail · 我的最愛")

with st.sidebar:
    st.header("⚙️ Scanner 條件")
    price_limit = st.number_input("CB 價格上限", 80.0, 200.0, 105.0, 0.5)
    premium_limit = st.number_input("溢價率上限 (%)", -50.0, 100.0, 15.0, 0.5)
    min_volume = st.number_input("最低成交量（張）", 0.0, 100000.0, 0.0, 1.0)
    st.divider()
    st.caption("資料來源：TPEx / TWSE 公開資料")
    st.caption("本工具僅供研究，不構成投資建議。")

@st.cache_data(ttl=900, show_spinner=False)
def cached_load():
    return load_market_data()

if "market" not in st.session_state:
    st.session_state.market = None
if "favorites" not in st.session_state:
    st.session_state.favorites = set()
if "selected_cb" not in st.session_state:
    st.session_state.selected_cb = None

c1, c2 = st.columns([1, 5])
with c1:
    refresh = st.button("🔄 更新資料", type="primary", use_container_width=True)
with c2:
    st.write("")

if refresh or st.session_state.market is None:
    with st.spinner("正在抓取 TPEx CB 行情、轉換價格與標的股票價格…"):
        try:
            st.session_state.market = cached_load()
            st.session_state.data_source = "LIVE"
        except Exception as e:
            cache_path = Path("data/latest.csv")
            if cache_path.exists():
                try:
                    st.session_state.market = pd.read_csv(cache_path)
                    st.session_state.data_source = "CACHE"
                    st.warning("⚠️ TPEx 即時抓取暫時失敗，已改用 GitHub Actions 最近一次成功更新的 data/latest.csv。")
                except Exception:
                    st.error(f"抓取失敗：{e}")
                    st.stop()
            else:
                st.error(f"抓取失敗：{e}")
                st.info("目前沒有可用的 data/latest.csv 快取；請先讓 GitHub Actions 成功跑一次更新。")
                st.stop()

if st.session_state.get("data_source") == "CACHE":
    st.caption("資料狀態：🟡 CACHE｜來源：data/latest.csv")
else:
    st.caption("資料狀態：🟢 LIVE｜來源：TPEx OpenAPI + TWSE 公開資料")

df = st.session_state.market.copy()
if df.empty:
    st.warning("目前沒有可用資料。")
    st.stop()

# Optional persisted previous snapshot generated by GitHub Actions.
previous = None
if os.path.exists("data/previous_market.csv"):
    try:
        previous = pd.read_csv("data/previous_market.csv")
    except Exception:
        previous = None

df = add_breakout_flags(df, previous)
df = apply_filters(df, price_limit, premium_limit, min_volume)
asof = df["資料日期"].dropna().iloc[0] if "資料日期" in df and df["資料日期"].notna().any() else "N/A"
avg_price = pd.to_numeric(df["CB價格"], errors="coerce").mean()

neg = df[df["溢價率"] < 0].copy()
cheap = df[(df["CB價格"] <= price_limit) & (df["溢價率"] <= premium_limit / 100)].copy()
breakouts = df[df["剛突破轉換價"]].copy()

m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("有效 CB", f"{len(df):,}")
m2.metric("負溢價", f"{len(neg):,}")
m3.metric(f"≤ {price_limit:g} 元", f"{len(df[df['CB價格'] <= price_limit]):,}")
m4.metric("全市場平均 CB 價格", f"{avg_price:.2f}")
m5.metric("剛突破轉換價", f"{len(breakouts):,}")
st.caption(f"資料日期：{asof}｜最後更新：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

DISPLAY = ["CB代號","CB名稱","標的股票代號","標的股價","轉換價格","距轉換價%","CB價格","轉換價值","溢價率","成交量(張)","成交金額(千元)","到期日","剛突破轉換價"]

def show_table(x):
    cols = [c for c in DISPLAY if c in x.columns]
    y = x[cols].copy()
    for c in ["CB價格", "標的股價", "轉換價格", "轉換價值"]:
        if c in y: y[c] = pd.to_numeric(y[c], errors="coerce").round(2)
    for c in ["溢價率", "距轉換價%"]:
        if c in y: y[c] = (pd.to_numeric(y[c], errors="coerce") * 100).round(2).map(lambda v: f"{v:.2f}%" if pd.notna(v) else "")
    return y

# Price distribution with overall average.
st.subheader("① Market Overview")
left, right = st.columns(2)
with left:
    st.markdown(f"**價格區間分布**　全市場平均：**{avg_price:.2f}**")
    bins = [0, 100, 105, 110, 120, float("inf")]
    labels = ["<100", "100–105", "105–110", "110–120", ">120"]
    price_series = pd.to_numeric(df["CB價格"], errors="coerce")
    dist = pd.Series({
        "<100": int((price_series < 100).sum()),
        "100–105": int(((price_series >= 100) & (price_series <= 105)).sum()),
        "105–110": int(((price_series > 105) & (price_series <= 110)).sum()),
        "110–120": int(((price_series > 110) & (price_series <= 120)).sum()),
        ">120": int((price_series > 120).sum()),
    })
    st.bar_chart(dist)
with right:
    st.markdown("**溢價率 vs CB 價格**")
    chart_df = df[["CB價格", "溢價率"]].dropna().rename(columns={"CB價格":"CB 價格", "溢價率":"溢價率"})
    st.scatter_chart(chart_df, x="CB 價格", y="溢價率", height=300)
    st.caption("左下角通常代表較低 CB 價格 + 較低轉換溢價的 Relative Value 區域。")

if not breakouts.empty:
    st.subheader("🚨 ② 轉換價突破觀察")
    st.markdown("**以下公司股價今日由轉換價以下突破至以上，請優先關注：**")
    st.dataframe(show_table(breakouts.sort_values("距轉換價%")), use_container_width=True, hide_index=True)
else:
    st.info("今日沒有偵測到『前一日 ≤ 轉換價、今日 > 轉換價』的剛突破標的。")

st.subheader("③ Scanner")
tab1, tab2, tab3 = st.tabs(["🔥 負溢價", "💰 低價低溢價", "📋 全部 CB"])
with tab1:
    st.dataframe(show_table(neg.sort_values("溢價率")), use_container_width=True, hide_index=True)
with tab2:
    st.dataframe(show_table(cheap.sort_values(["溢價率", "CB價格"])), use_container_width=True, hide_index=True)
with tab3:
    st.dataframe(show_table(df.sort_values("溢價率")), use_container_width=True, hide_index=True)

st.subheader("④ 個股研究")
if st.session_state.selected_cb is None:
    options = df["CB代號"].dropna().astype(str).tolist()
    selected = st.selectbox("選擇一檔 CB", options, index=0 if options else None)
    if selected:
        st.session_state.selected_cb = selected
else:
    selected = st.selectbox("選擇一檔 CB", df["CB代號"].astype(str).tolist(), index=df["CB代號"].astype(str).tolist().index(st.session_state.selected_cb) if st.session_state.selected_cb in set(df["CB代號"].astype(str)) else 0)
    st.session_state.selected_cb = selected

row = df[df["CB代號"].astype(str) == str(selected)].iloc[0]
col1, col2 = st.columns([1, 2])
with col1:
    st.markdown(f"### {row.get('CB代號','')} {row.get('CB名稱','')}")
    st.write(f"標的：{row.get('標的股票代號','')} {row.get('標的股票名稱','')}")
    st.metric("CB 價格", f"{row['CB價格']:.2f}")
    st.metric("標的股價", f"{row['標的股價']:.2f}")
    st.metric("轉換價格", f"{row['轉換價格']:.2f}")
    st.metric("距轉換價", f"{row['距轉換價%']*100:.2f}%")
    st.metric("轉換價值", f"{row['轉換價值']:.2f}")
    st.metric("溢價率", f"{row['溢價率']*100:.2f}%")
with col2:
    st.markdown("#### 🏢 公司業務摘要")
    if st.button("✨ 產生公司業務摘要", key="company_summary"):
        with st.spinner("Gemini 整理公司業務…"):
            try:
                st.session_state.company_summary = generate_company_summary(str(row.get("標的股票代號", "")), str(row.get("標的股票名稱", "")))
            except Exception as e:
                st.error(str(e))
    st.info(st.session_state.get("company_summary", "按下按鈕後，Gemini 會用簡短篇幅整理公司主要產品、服務與產業鏈位置。"))
    if bool(row.get("剛突破轉換價", False)):
        st.markdown('<div class="breakout"><b>🔥 剛突破轉換價</b>：今日股價已由前一交易日轉換價以下突破至以上，建議列入今日重點觀察。</div>', unsafe_allow_html=True)

st.subheader("⑤ 我的最愛清單")
with st.expander("加入／移除最愛", expanded=False):
    fav_choices = st.multiselect("選擇 CB", df["CB代號"].astype(str).tolist(), default=sorted(st.session_state.favorites & set(df["CB代號"].astype(str))))
    st.session_state.favorites = set(fav_choices)

favorites_df = df[df["CB代號"].astype(str).isin(st.session_state.favorites)].copy()
if favorites_df.empty:
    st.info("目前沒有最愛標的。請在上方加入 CB；重新整理網頁後 Streamlit session 可能重置，若要長期保存可把 favorites.csv 納入 GitHub。")
else:
    st.dataframe(show_table(favorites_df.sort_values("溢價率")), use_container_width=True, hide_index=True)

st.subheader("⑥ Gemini 每日投資摘要")
if st.button("🤖 產生今日 CB 日報"):
    with st.spinner("Gemini 分析市場…"):
        try:
            st.markdown(generate_report(neg, cheap, asof))
        except Exception as e:
            st.error(str(e))

st.divider()
st.download_button("⬇️ 下載全部 CB CSV", df.to_csv(index=False).encode("utf-8-sig"), file_name=f"cb_market_{asof}.csv", mime="text/csv")
